In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(6,5,4)]], dtype=float)

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [8]:
c

array([[[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 3. ,  2. ,  1. ],
        [ 6. ,  5. ,  4. ]]])

In [9]:
np.zeros((2,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
d = np.arange(10,25,5)

In [12]:
d

array([10, 15, 20])

In [13]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [14]:
e = np.full((2,2),7)

In [15]:
e

array([[7, 7],
       [7, 7]])

In [16]:
f = np.eye(2)

In [17]:
f

array([[ 1.,  0.],
       [ 0.,  1.]])

In [28]:
np.random.random((3,3))

array([[ 0.66937974,  0.08942375,  0.28147314],
       [ 0.19165665,  0.05080461,  0.45894517],
       [ 0.76544745,  0.30699261,  0.22986518]])

In [29]:
np.empty((3,5))

array([[  2.68156159e+154,   2.68156159e+154,   8.89318163e-323,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   2.68156159e+154]])

In [30]:
a.shape

(3,)

In [31]:
len(b)

2

In [32]:
b.ndim

2

In [33]:
e.size

4

In [34]:
b.dtype

dtype('float64')

In [35]:
b.dtype.name

'float64'

In [36]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a-b

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [39]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [40]:
b+a

array([[ 2.5,  4. ,  6. ],
       [ 5. ,  7. ,  9. ]])

In [41]:
np.add(b,a)

array([[ 2.5,  4. ,  6. ],
       [ 5. ,  7. ,  9. ]])

In [42]:
a/b

array([[ 0.66666667,  1.        ,  1.        ],
       [ 0.25      ,  0.4       ,  0.5       ]])

In [43]:
np.divide(a,b)

array([[ 0.66666667,  1.        ,  1.        ],
       [ 0.25      ,  0.4       ,  0.5       ]])

In [44]:
a*b

array([[  1.5,   4. ,   9. ],
       [  4. ,  10. ,  18. ]])

In [45]:
np.multiply(a,b)

array([[  1.5,   4. ,   9. ],
       [  4. ,  10. ,  18. ]])

In [46]:
np.exp(b)

array([[   4.48168907,    7.3890561 ,   20.08553692],
       [  54.59815003,  148.4131591 ,  403.42879349]])

In [47]:
np.sqrt(b)

array([[ 1.22474487,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [48]:
np.log(a)

array([ 0.        ,  0.69314718,  1.09861229])

In [49]:
e.dot(f)

array([[ 7.,  7.],
       [ 7.,  7.]])

In [50]:
a==b

array([[False,  True,  True],
       [False, False, False]], dtype=bool)

In [51]:
a<2

array([ True, False, False], dtype=bool)

In [52]:
np.array_equal(a,b)

False

In [53]:
a.sum()

6

In [54]:
a.min()

1

In [55]:
b.max(axis=0)

array([ 4.,  5.,  6.])

In [56]:
b.max(axis=1)

array([ 3.,  6.])

In [57]:
b.cumsum(axis=1)

array([[  1.5,   3.5,   6.5],
       [  4. ,   9. ,  15. ]])

In [58]:
b.mean()

3.5833333333333335

In [61]:
np.median(a)

2.0

In [63]:
np.corrcoef(b)

array([[ 1.        ,  0.98198051],
       [ 0.98198051,  1.        ]])

In [64]:
np.std(b)

1.5920810978785667

In [65]:
a.view()

array([1, 2, 3])

In [66]:
np.copy(a)

array([1, 2, 3])

In [67]:
h = a.copy()

In [69]:
np.array_equal(a,h)

True

In [72]:
c.sort()
c

array([[[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]]])

In [74]:
c.sort(axis=0)
c

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]]])

In [76]:
a[2]

3

In [77]:
b[1,2]

6.0

In [78]:
b[0:2,1]

array([ 2.,  5.])

In [79]:
b[:1]

array([[ 1.5,  2. ,  3. ]])

In [80]:
c[1,...]

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [81]:
a[a<2]

array([1])

In [82]:
b[[1,0,1,0],[0,2,1,0]]

array([ 4. ,  3. ,  5. ,  1.5])

In [83]:
i = np.transpose(b)

In [84]:
i

array([[ 1.5,  4. ],
       [ 2. ,  5. ],
       [ 3. ,  6. ]])

In [85]:
i.T

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [86]:
b.ravel()

array([ 1.5,  2. ,  3. ,  4. ,  5. ,  6. ])

In [88]:
g = a-b
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [90]:
h.resize(2,6)
h

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [91]:
np.append(h,g)

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [93]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [94]:
np.delete(a,[1])

array([1, 3])

In [95]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [96]:
np.vstack((a,b))

array([[ 1. ,  2. ,  3. ],
       [ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [98]:
np.r_[e,f]

array([[ 7.,  7.],
       [ 7.,  7.],
       [ 1.,  0.],
       [ 0.,  1.]])

In [99]:
np.hstack((e,f))

array([[ 7.,  7.,  1.,  0.],
       [ 7.,  7.,  0.,  1.]])

In [100]:
np.vstack((e,f))

array([[ 7.,  7.],
       [ 7.,  7.],
       [ 1.,  0.],
       [ 0.,  1.]])

In [101]:
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [102]:
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [103]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [105]:
np.vsplit(c,2)

[array([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]]), array([[[ 1.5,  2. ,  3. ],
         [ 4. ,  5. ,  6. ]]])]