In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([(1+5j,2j,3j),(4j,5j,6j)])

In [4]:
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([[ 1.+5.j,  0.+2.j,  0.+3.j],
       [ 0.+4.j,  0.+5.j,  0.+6.j]])

In [7]:
c

array([[[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 3. ,  2. ,  1. ],
        [ 4. ,  5. ,  6. ]]])

In [8]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [9]:
np.ogrid[0:2,0:2]

[array([[0],
        [1]]), array([[0, 1]])]

In [10]:
np.r_[3,[0]*5,-1:1:10j]

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [11]:
np.c_[b,b]

array([[ 1.+5.j,  0.+2.j,  0.+3.j,  1.+5.j,  0.+2.j,  0.+3.j],
       [ 0.+4.j,  0.+5.j,  0.+6.j,  0.+4.j,  0.+5.j,  0.+6.j]])

In [12]:
np.transpose(b)

array([[ 1.+5.j,  0.+4.j],
       [ 0.+2.j,  0.+5.j],
       [ 0.+3.j,  0.+6.j]])

In [13]:
b.flatten()

array([ 1.+5.j,  0.+2.j,  0.+3.j,  0.+4.j,  0.+5.j,  0.+6.j])

In [14]:
np.hstack((b,b))

array([[ 1.+5.j,  0.+2.j,  0.+3.j,  1.+5.j,  0.+2.j,  0.+3.j],
       [ 0.+4.j,  0.+5.j,  0.+6.j,  0.+4.j,  0.+5.j,  0.+6.j]])

In [15]:
np.vstack((a,b))

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [ 1.+5.j,  0.+2.j,  0.+3.j],
       [ 0.+4.j,  0.+5.j,  0.+6.j]])

In [16]:
np.hsplit(c,2)

[array([[[ 1.5,  2. ,  3. ]],
 
        [[ 3. ,  2. ,  1. ]]]), array([[[ 4.,  5.,  6.]],
 
        [[ 4.,  5.,  6.]]])]

In [17]:
np.vsplit(b,2)

[array([[ 1.+5.j,  0.+2.j,  0.+3.j]]), array([[ 0.+4.j,  0.+5.j,  0.+6.j]])]

In [18]:
from numpy import poly1d

In [19]:
p = poly1d([3,4,5])

In [20]:
p

poly1d([3, 4, 5])

In [21]:
def myfunc(a):
    if a < 0:
        return a*2
    else:
        return a/2

In [22]:
np.vectorize(myfunc)

In [23]:
np.angle(b,deg=True)

array([[ 78.69006753,  90.        ,  90.        ],
       [ 90.        ,  90.        ,  90.        ]])

In [24]:
g = np.linspace(0,np.pi,num=5)

In [25]:
g

array([ 0.        ,  0.78539816,  1.57079633,  2.35619449,  3.14159265])

In [26]:
g[3:] += np.pi
g

array([ 0.        ,  0.78539816,  1.57079633,  5.49778714,  6.28318531])

In [27]:
np.unwrap(g)

array([ 0.        ,  0.78539816,  1.57079633, -0.78539816,  0.        ])

In [28]:
np.logspace(0,10,7)

array([  1.00000000e+00,   4.64158883e+01,   2.15443469e+03,
         1.00000000e+05,   4.64158883e+06,   2.15443469e+08,
         1.00000000e+10])

In [29]:
np.select([c<4],[c*2])

array([[[ 3.,  4.,  6.],
        [ 0.,  0.,  0.]],

       [[ 6.,  4.,  2.],
        [ 0.,  0.,  0.]]])

In [30]:
from scipy import misc

In [31]:
misc.factorial(a)

array([ 1.,  2.,  6.])

In [32]:
misc.comb(10,3,exact=True)

120

In [33]:
misc.central_diff_weights(3)

array([-0.5,  0. ,  0.5])

In [34]:
misc.derivative(myfunc,1.0)

0.5

In [35]:
from scipy import linalg, sparse

In [36]:
A = np.matrix(np.random.random((2,2)))

In [37]:
A

matrix([[ 0.06616415,  0.3471567 ],
        [ 0.26668206,  0.43751434]])

In [38]:
B = np.asmatrix(b)

In [39]:
B

matrix([[ 1.+5.j,  0.+2.j,  0.+3.j],
        [ 0.+4.j,  0.+5.j,  0.+6.j]])

In [40]:
C = np.mat(np.random.random((10,5)))

In [41]:
C

matrix([[ 0.35358139,  0.7773458 ,  0.18955362,  0.56844967,  0.37357966],
        [ 0.90395375,  0.26151726,  0.15722046,  0.74888368,  0.10866204],
        [ 0.0880758 ,  0.90533266,  0.97170436,  0.19405352,  0.45912404],
        [ 0.88737984,  0.02870651,  0.89974578,  0.23953418,  0.05099484],
        [ 0.13452213,  0.64768511,  0.19914959,  0.24957695,  0.11041997],
        [ 0.01029463,  0.03094643,  0.49657296,  0.81246679,  0.61242679],
        [ 0.04582707,  0.36758689,  0.620671  ,  0.42828803,  0.82585181],
        [ 0.94973533,  0.73183344,  0.45202226,  0.24642228,  0.0788892 ],
        [ 0.44510302,  0.25657062,  0.15258075,  0.88402829,  0.15216697],
        [ 0.03306641,  0.33648283,  0.70414044,  0.33490067,  0.7204011 ]])

In [42]:
D = np.mat([[3,4],[5,6]])

In [43]:
D

matrix([[3, 4],
        [5, 6]])

In [44]:
A.I

matrix([[-6.87562144,  5.45563379],
        [ 4.19095951, -1.03978229]])

In [45]:
linalg.inv(A)

array([[-6.87562144,  5.45563379],
       [ 4.19095951, -1.03978229]])

In [46]:
A.T

matrix([[ 0.06616415,  0.26668206],
        [ 0.3471567 ,  0.43751434]])

In [47]:
A.H

matrix([[ 0.06616415,  0.26668206],
        [ 0.3471567 ,  0.43751434]])

In [48]:
np.trace(A)

0.50367849641462925

In [49]:
linalg.norm(A)

0.62244163680705022

In [50]:
linalg.norm(A,1)

0.7846710419583453

In [51]:
linalg.norm(A,np.inf)

0.7041964052227596

In [52]:
np.linalg.matrix_rank(c)

array([2, 2])

In [53]:
linalg.det(A)

-0.06363269816140685

In [54]:
linalg.solve(A,b)

array([[-6.87562144-12.555572j  ,  0.00000000+13.5269261j ,
         0.00000000+12.10693845j],
       [ 4.19095951+16.79566839j,  0.00000000 +3.18300755j,
         0.00000000 +6.33418477j]])

In [55]:
E = np.mat(a).T

In [56]:
E

matrix([[1],
        [2],
        [3]])

In [57]:
F = np.eye(3, k=1)

In [58]:
F

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [66]:
linalg.lstsq(F,E)

(array([[ 0.],
        [ 1.],
        [ 2.]]), array([], dtype=float64), 2, array([ 1.,  1.,  0.]))

In [67]:
linalg.pinv(C)

array([[ 0.74896467, -1.46581291, -0.98272866,  0.19484895,  0.85089693,
        -0.45863337,  0.06491198, -0.21619468,  1.60243533, -0.12798159],
       [-0.2910461 ,  1.76770317,  0.06362669, -0.51006433, -0.95912774,
         0.28093454,  0.54842833, -0.5112353 ,  0.39221766,  0.71753069],
       [ 0.04151159,  0.39679011, -0.27934765, -0.15534517,  0.13662608,
         1.08137927, -0.21474808,  0.81229091, -0.01060749, -0.15190294],
       [-0.12706517, -1.17852875,  0.05811421,  0.79895206,  0.97327752,
        -0.399843  ,  0.67964468,  0.5724017 , -0.29256905,  0.36519055],
       [ 0.52766295,  1.15322389,  1.83092648, -0.13740579, -0.51177294,
        -0.06289989, -0.2926491 , -0.12969359, -0.58691986, -0.11155583]])

In [69]:
linalg.pinv2(C)

array([[ 0.74896467, -1.46581291, -0.98272866,  0.19484895,  0.85089693,
        -0.45863337,  0.06491198, -0.21619468,  1.60243533, -0.12798159],
       [-0.2910461 ,  1.76770317,  0.06362669, -0.51006433, -0.95912774,
         0.28093454,  0.54842833, -0.5112353 ,  0.39221766,  0.71753069],
       [ 0.04151159,  0.39679011, -0.27934765, -0.15534517,  0.13662608,
         1.08137927, -0.21474808,  0.81229091, -0.01060749, -0.15190294],
       [-0.12706517, -1.17852875,  0.05811421,  0.79895206,  0.97327752,
        -0.399843  ,  0.67964468,  0.5724017 , -0.29256905,  0.36519055],
       [ 0.52766295,  1.15322389,  1.83092648, -0.13740579, -0.51177294,
        -0.06289989, -0.2926491 , -0.12969359, -0.58691986, -0.11155583]])

In [70]:
G = np.mat(np.identity(2))

In [71]:
G

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [72]:
C[C>0.5] = 0

In [73]:
C

matrix([[ 0.35358139,  0.        ,  0.18955362,  0.        ,  0.37357966],
        [ 0.        ,  0.26151726,  0.15722046,  0.        ,  0.10866204],
        [ 0.0880758 ,  0.        ,  0.        ,  0.19405352,  0.45912404],
        [ 0.        ,  0.02870651,  0.        ,  0.23953418,  0.05099484],
        [ 0.13452213,  0.        ,  0.19914959,  0.24957695,  0.11041997],
        [ 0.01029463,  0.03094643,  0.49657296,  0.        ,  0.        ],
        [ 0.04582707,  0.36758689,  0.        ,  0.42828803,  0.        ],
        [ 0.        ,  0.        ,  0.45202226,  0.24642228,  0.0788892 ],
        [ 0.44510302,  0.25657062,  0.15258075,  0.        ,  0.15216697],
        [ 0.03306641,  0.33648283,  0.        ,  0.33490067,  0.        ]])

In [74]:
H = sparse.csr_matrix(C)

In [75]:
H

<10x5 sparse matrix of type '<class 'numpy.float64'>'
	with 32 stored elements in Compressed Sparse Row format>

In [76]:
I = sparse.csc_matrix(D)

In [77]:
I

<2x2 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Column format>

In [78]:
J = sparse.dok_matrix(A)

In [79]:
J

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Dictionary Of Keys format>

In [82]:
sparse.isspmatrix(A)

False

In [83]:
sparse.linalg.inv(I)

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Column format>

In [84]:
sparse.linalg.norm(I)

9.2736184954957039

In [89]:
sparse.linalg.spsolve(I,I)

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Column format>

In [90]:
sparse.linalg.expm(I)

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Column format>

In [91]:
np.add(A,D)

matrix([[ 3.06616415,  4.3471567 ],
        [ 5.26668206,  6.43751434]])

In [92]:
np.subtract(A,D)

matrix([[-2.93383585, -3.6528433 ],
        [-4.73331794, -5.56248566]])

In [93]:
np.divide(A,D)

matrix([[ 0.02205472,  0.08678917],
        [ 0.05333641,  0.07291906]])

In [94]:
np.multiply(A,D)

matrix([[ 0.19849246,  1.38862679],
        [ 1.33341031,  2.62508606]])

In [95]:
A @ D

matrix([[ 1.93427595,  2.3475968 ],
        [ 2.9876179 ,  3.69181431]])

In [96]:
np.dot(A,D)

matrix([[ 1.93427595,  2.3475968 ],
        [ 2.9876179 ,  3.69181431]])

In [97]:
np.vdot(A,D)

matrix([[ 0.19849246]])

In [98]:
np.inner(A,D)

matrix([[ 1.58711925,  2.41376096],
        [ 2.55010356,  3.95849637]])

In [99]:
np.outer(A,D)

array([[ 0.19849246,  0.26465661,  0.33082076,  0.39698492],
       [ 1.0414701 ,  1.38862679,  1.73578349,  2.08294019],
       [ 0.80004619,  1.06672825,  1.33341031,  1.60009237],
       [ 1.31254303,  1.75005737,  2.18757172,  2.62508606]])

In [100]:
np.tensordot(A,D)

array(5.545615622224386)

In [101]:
np.kron(A,D)

matrix([[ 0.19849246,  0.26465661,  1.0414701 ,  1.38862679],
        [ 0.33082076,  0.39698492,  1.73578349,  2.08294019],
        [ 0.80004619,  1.06672825,  1.31254303,  1.75005737],
        [ 1.33341031,  1.60009237,  2.18757172,  2.62508606]])

In [102]:
linalg.expm(A)

array([[ 1.12503916,  0.45609562],
       [ 0.35036778,  1.61292027]])

In [105]:
linalg.logm(A)

array([[-1.83581611+2.3890283j ,  0.85726149-1.5298482j ],
       [ 0.65853911-1.17521302j, -0.91881171+0.75256435j]])

In [107]:
linalg.signm(A)

array([[-0.52090265,  0.97393162],
       [ 0.74816385,  0.52090265]])

In [108]:
linalg.sqrtm(A)

array([[ 0.18683076+0.24595574j,  0.37979836-0.15750125j],
       [ 0.29175704-0.12099078j,  0.59309743+0.07747816j]])

In [109]:
linalg.funm(A, lambda x: x*x)

array([[ 0.09695816,  0.17485536],
       [ 0.13432202,  0.28399926]])

In [110]:
la,v = linalg.eig(A)

In [111]:
la

array([-0.10460949+0.j,  0.60828799+0.j])

In [112]:
v

array([[-0.89730815, -0.53927126],
       [ 0.44140466, -0.84213212]])

In [113]:
linalg.eigvals(A)

array([-0.10460949+0.j,  0.60828799+0.j])

In [114]:
U,s,Vh = linalg.svd(B)

In [115]:
U

array([[-0.56260618 +7.06586639e-19j,  0.82672503 +0.00000000e+00j],
       [-0.82386933 -6.86557772e-02j, -0.56066281 -4.67219005e-02j]])

In [116]:
s

array([ 10.47751754,   2.49431877])

In [117]:
Vh

array([[-0.07990722 -5.83011023e-01j, -0.03276338 -5.00553588e-01j,
        -0.03931606 -6.32882215e-01j],
       [ 0.25651791 +7.58112384e-01j, -0.09365663 -4.60993186e-01j,
        -0.11238796 -3.54325894e-01j],
       [-0.11479126 -3.56425932e-04j, -0.68803469 -2.31721068e-01j,
         0.64988974 +1.93338508e-01j]])

In [118]:
M,N = B.shape

In [119]:
Sig = linalg.diagsvd(s,M,N)

In [120]:
Sig

array([[ 10.47751754,   0.        ,   0.        ],
       [  0.        ,   2.49431877,   0.        ]])

In [121]:
P,L,U = linalg.lu(C)

In [122]:
P

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [123]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.10295835,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.02312864,  0.07331314,  1.        ,  0.        ,  0.        ],
       [ 0.30222694, -0.22728368,  0.30244107,  1.        ,  0.        ],
       [ 0.19787734, -0.14880967, -0.06582411,  0.71747605,  1.        ],
       [ 0.        ,  0.08414117,  0.00267467,  0.57119035,  0.04483294],
       [ 0.        ,  0.76652886,  0.3425004 , -0.89092724,  0.46124763],
       [ 0.        ,  0.        ,  0.91466249,  0.77196795,  0.08765612],
       [ 0.79438101, -0.59739823,  0.11930813,  0.72837506,  0.51986873],
       [ 0.07428934,  0.93039138,  0.00663872, -0.17778755,  0.03723689]])

In [124]:
U

array([[ 0.44510302,  0.25657062,  0.15258075,  0.        ,  0.15216697],
       [ 0.        ,  0.3411708 , -0.01570946,  0.42828803, -0.01566686],
       [ 0.        ,  0.        ,  0.49419569, -0.03139914, -0.00237083],
       [ 0.        ,  0.        ,  0.        ,  0.35641622,  0.06158723],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.38233885]])

In [125]:
la,v = sparse.linalg.eigs(F,1)

In [126]:
la

array([  3.35736929e-06+0.j])

In [127]:
v

array([[ -1.00000000e+00+0.j],
       [ -3.35736929e-06+0.j],
       [ -1.12719833e-11+0.j]])

In [128]:
sparse.linalg.svds(H,2)

(array([[ 0.45127862,  0.38004507],
        [-0.03047612,  0.2193628 ],
        [ 0.09554649,  0.31536308],
        [-0.19692423,  0.14730946],
        [ 0.02753283,  0.31375843],
        [ 0.29922943,  0.25678634],
        [-0.59790081,  0.36261255],
        [ 0.11893194,  0.37081703],
        [ 0.18037981,  0.40291304],
        [-0.50303793,  0.30095869]]),
 array([ 0.7042283 ,  1.04024167]),
 array([[ 0.29964314, -0.49291816,  0.44886692, -0.59212533,  0.33934017],
        [ 0.39693718,  0.39171399,  0.50528603,  0.50205766,  0.42617503]]))